apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blocky.fullname" . }}
  labels:
    {{- include "blocky.labels" . | nindent 4 }}
data:
  config.yml: |
    {{- .Values.config | toYaml | nindent 4 }}
