{{- if and .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "blocky.fullname" . }}-dns
  labels:
    {{- include "blocky.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    - port: {{ .Values.config.ports.dns }}
      targetPort: dns-tcp
      protocol: TCP
      name: dns-tcp
    - port: {{ .Values.config.ports.dns }}
      targetPort: dns-udp
      protocol: UDP
      name: dns-udp
    {{- with .Values.config.ports.tls }}
    - port: {{ . }}
      targetPort: dns-tls
      protocol: TCP
      name: dns-tls
    {{- end }}
    {{- with .Values.config.ports.http }}
    - port: {{ . }}
      targetPort: http
      protocol: TCP
      name: http
    {{- end }}
    {{- with .Values.config.ports.https }}
    - port: {{ . }}
      targetPort: https
      protocol: TCP
      name: https
    {{- end }}
  selector:
    {{- include "blocky.selectorLabels" . | nindent 4 }}
{{- end }}
