{{- if and .Values.ui.enabled .Values.ui.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "blocky.fullname" . }}-ui
  labels:
    {{- include "blocky.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: ui-http
      protocol: TCP
      name: ui-http
  selector:
    {{- include "blocky.selectorLabels" . | nindent 4 }}
{{- end }}
